runtime: nodejs22
instance_class: F4
service: beer-fermentation-gravity-tracker-frontend
env_variables:
  REACT_APP_CLOUD_FUNCTIONS_URL: "https://us-east1-beer-fermentation-tracker.cloudfunctions.net"
