name: GCP Beer Fermentation App CICD

on:
  push:
  pull_request:
    
env:
  GOOGLE_APPLICATION_CREDENTIALS_DATA: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_DATA }}
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_DATA }}
  
jobs:
  terraform-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "terraform"
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.0
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -no-color -input=false -var deployment_version=1

  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "cloud_functions/add_batch_reading"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          
      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: "latest"
          # this format is used to also display the file & line number in the workflow's output
          # without this, lint errors are only displayed in the "Files changed" tab
          # see this issue for more information
          # https://github.com/golangci/golangci-lint-action/issues/119
          args: --timeout=5m --out-${NO_FUTURE}format colored-line-number
